/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/strings/count.py

load("build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/home/jared/clone/pjs/test/py2js/strings/count.py', function (_) {
    _.__doc__ = "";
    _.txt = $b.str('the quick brown fox jumped over the lazy dogthe');
    _.c = _.txt.count($b.str('the'));
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 0, -20);
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 3);
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 4, 15);
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 1, $b.len(_.txt));
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 4, $b.sub($b.len(_.txt), 1));
    $b.print(_.c);//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/home/jared/clone/pjs/test/py2js/strings/count.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

