/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /Users/jared/clone/PJs/test/py2js/strings/count.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/Users/jared/clone/PJs/test/py2js/strings/count.py', function (_) {
    _.__doc__ = "";
    _.txt = $b.str('the quick brown fox jumped over the lazy dogthe');
    _.c = _.txt.count($b.str('the'));
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 0, -20);
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 3);
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 4, 15);
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 1, $b.len(_.txt));
    $b.print(_.c);//, true
    _.c = _.txt.count($b.str('the'), 4, $b.sub($b.len(_.txt), 1));
    $b.print(_.c);//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/Users/jared/clone/PJs/test/py2js/strings/count.py', ['/Users/jared/clone/PJs', '/Users/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/pip-1.3-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg', '/Users/jared/.venv/default/lib/python27.zip', '/Users/jared/.venv/default/lib/python2.7', '/Users/jared/.venv/default/lib/python2.7/plat-darwin', '/Users/jared/.venv/default/lib/python2.7/plat-mac', '/Users/jared/.venv/default/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/Extras/lib/python', '/Users/jared/.venv/default/lib/python2.7/lib-tk', '/Users/jared/.venv/default/lib/python2.7/lib-old', '/Users/jared/.venv/default/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/lib/python2.7/site-packages']);

