/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/strings/split.py

load("build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/home/jared/clone/pjs/test/py2js/strings/split.py', function (_) {
    _.__doc__ = "";
    _.s = $b.str('the     quick brown fox jumped over the lazy dog');
    _.t = _.s.split($b.str(' '));
    var __pjs_iter_1 = $b.foriter(_.t);
    while (__pjs_iter_1.trynext()) {
        _.v = __pjs_iter_1.value;
    
        $b.print(_.v);//, true
    }
    _.r = _.s.split($b.str('e'));
    var __pjs_iter_1 = $b.foriter(_.r);
    while (__pjs_iter_1.trynext()) {
        _.v = __pjs_iter_1.value;
    
        $b.print(_.v);//, true
    }
    _.x = _.s.split();
    var __pjs_iter_1 = $b.foriter(_.x);
    while (__pjs_iter_1.trynext()) {
        _.v = __pjs_iter_1.value;
    
        $b.print(_.v);//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/home/jared/clone/pjs/test/py2js/strings/split.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

