/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/PJs/test/py2js/strings/string_format_u.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/home/jared/clone/PJs/test/py2js/strings/string_format_u.py', function (_) {
    _.__doc__ = "";
    _.a = $b._float(1.123456);
    _.b = 10;
    _.c = -30;
    _.d = 34;
    _.e = $b._float(123.456);
    _.f = 19892122;
    _.s = $b.mod($b.str('b=%u'), _.b);
    $b.print(_.s);//, true
    _.s = $b.mod($b.str('b,c,d=%u+%u+%u'), $b.tuple([_.b, _.c, _.d]));
    $b.print(_.s);//, true
    _.s = $b.mod($b.str('b=%(b)0u and c=%(c)u and d=%(d)u'), $b.dict([[$b.str('b'), _.b], [$b.str('c'), _.c], [$b.str('d'), _.d]]));
    $b.print(_.s);//, true
    _.s = $b.mod($b.str('e=%020u e=%+u e=%20u e=%-20u (e=%- 20u)'), $b.tuple([_.e, _.e, _.e, _.e, _.e]));
    $b.print(_.s);//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/home/jared/clone/PJs/test/py2js/strings/string_format_u.py', ['/home/jared/clone/PJs', '/home/jared/.venv/default/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/home/jared/.venv/default/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg', '/home/jared/.venv/default/local/lib/python2.7/site-packages/PJs-0.0.1-py2.7.egg', '/home/jared/.venv/default/local/lib/python2.7/site-packages/pbj-0.1.2-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/PJs-0.0.1-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/pbj-0.1.2-py2.7.egg', '/home/jared/clone/PJs', '/home/jared/python', '/home/jared/.venv/default/lib/python2.7', '/home/jared/.venv/default/lib/python2.7/plat-i386-linux-gnu', '/home/jared/.venv/default/lib/python2.7/lib-tk', '/home/jared/.venv/default/lib/python2.7/lib-old', '/home/jared/.venv/default/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-i386-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/jared/.venv/default/local/lib/python2.7/site-packages', '/home/jared/.venv/default/lib/python2.7/site-packages']);

