/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/PJs/test/py2js/strings/string_format_efg.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/home/jared/clone/PJs/test/py2js/strings/string_format_efg.py', function (_) {
    _.__doc__ = "";
    _.a = $b._float(1.123456);
    _.b = $b._float(3.24324e-10);
    _.c = $b._float(18347894.2131);
    _.d = $b._float(0.0);
    _.e = $b._float(-1324323.456);
    _.f = $b._float(-1.9892122e-11);
    _.vars = $b.list([_.a, _.b, _.c, _.d, _.e, _.f]);
    _.codes = $b.list([$b.str('e'), $b.str('E'), $b.str('f'), $b.str('F'), $b.str('g'), $b.str('G')]);
    _.fmts = $b.list([$b.str('a=%e'), $b.str('a=%10.5e'), $b.str('a=%+10.5e'), $b.str('a=%#e')]);
    var __pjs_iter_1 = $b.foriter(_.codes);
    while (__pjs_iter_1.trynext()) {
        _.code = __pjs_iter_1.value;
    
        var __pjs_iter_2 = $b.foriter(_.fmts);
        while (__pjs_iter_2.trynext()) {
            _.fmt = __pjs_iter_2.value;
        
            _.fmt = _.fmt.replace($b.str('e'), _.code);
            var __pjs_iter_3 = $b.foriter(_.vars);
            while (__pjs_iter_3.trynext()) {
                _.v = __pjs_iter_3.value;
            
                $b.print($b.add(_.fmt, $b.str(':')), $b.mod(_.fmt, _.v));//, true
            }
        }
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/home/jared/clone/PJs/test/py2js/strings/string_format_efg.py', ['/home/jared/clone/PJs', '/home/jared/.venv/default/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/home/jared/.venv/default/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg', '/home/jared/.venv/default/local/lib/python2.7/site-packages/PJs-0.0.1-py2.7.egg', '/home/jared/.venv/default/local/lib/python2.7/site-packages/pbj-0.1.2-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/PJs-0.0.1-py2.7.egg', '/home/jared/.venv/default/lib/python2.7/site-packages/pbj-0.1.2-py2.7.egg', '/home/jared/clone/PJs', '/home/jared/python', '/home/jared/.venv/default/lib/python2.7', '/home/jared/.venv/default/lib/python2.7/plat-i386-linux-gnu', '/home/jared/.venv/default/lib/python2.7/lib-tk', '/home/jared/.venv/default/lib/python2.7/lib-old', '/home/jared/.venv/default/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-i386-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/jared/.venv/default/local/lib/python2.7/site-packages', '/home/jared/.venv/default/lib/python2.7/site-packages']);

