/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/strings/string_format_x.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/strings/string_format_x.py', function (_) {
    _.__doc__ = "";
    _.vals = $b.list([0, 10, -30, 173247, 123, 19892122]);
    _.formats = $b.list([$b.str('%x'), $b.str('%020x'), $b.str('%X'), $b.str('%020X'), $b.str('%-20x'), $b.str('%#x')]);
    var __pjs_iter0 = $b.foriter(_.vals);
    while (__pjs_iter0.trynext()) {
        _.val = __pjs_iter0.value;
    
        var __pjs_iter1 = $b.foriter(_.formats);
        while (__pjs_iter1.trynext()) {
            _.fmt = __pjs_iter1.value;
        
            $b.print($b.add(_.fmt, $b.str(':')), $b.mod(_.fmt, _.val));//, true
        }
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/strings/string_format_x.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

