/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /Users/jared/clone/PJs/test/py2js/strings/string_format_x.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/Users/jared/clone/PJs/test/py2js/strings/string_format_x.py', function (_) {
    _.__doc__ = "";
    _.vals = $b.list([0, 10, -30, 173247, 123, 19892122]);
    _.formats = $b.list([$b.str('%x'), $b.str('%020x'), $b.str('%X'), $b.str('%020X'), $b.str('%-20x'), $b.str('%#x')]);
    var __pjs_iter_1 = $b.foriter(_.vals);
    while (__pjs_iter_1.trynext()) {
        _.val = __pjs_iter_1.value;
    
        var __pjs_iter_2 = $b.foriter(_.formats);
        while (__pjs_iter_2.trynext()) {
            _.fmt = __pjs_iter_2.value;
        
            $b.print($b.add(_.fmt, $b.str(':')), $b.mod(_.fmt, _.val));//, true
        }
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/Users/jared/clone/PJs/test/py2js/strings/string_format_x.py', ['/Users/jared/clone/PJs', '/Users/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/pip-1.3-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg', '/Users/jared/.venv/default/lib/python27.zip', '/Users/jared/.venv/default/lib/python2.7', '/Users/jared/.venv/default/lib/python2.7/plat-darwin', '/Users/jared/.venv/default/lib/python2.7/plat-mac', '/Users/jared/.venv/default/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/Extras/lib/python', '/Users/jared/.venv/default/lib/python2.7/lib-tk', '/Users/jared/.venv/default/lib/python2.7/lib-old', '/Users/jared/.venv/default/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/lib/python2.7/site-packages']);

