/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/lists/in.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/lists/in.py', function (_) {
    _.__doc__ = "";
    _.l = $b.list([$b.str('a'), $b.str('b'), $b.str('c')]);
    _.intest = $def(function $_intest(item, list) { // 5
        if ($b.bool($b.do_ops(item, 'in', list)) === true) {
            $b.print($b.add($b.str(item), $b.str(' is in list')));//, true
        } else $b.print($b.add($b.str(item), $b.str(' is not in list')));//, true
    });
    _.intest.__module__ = _.__name__;
    _.intest.__name__ = $b.str("intest");
    _.intest($b.str('a'), _.l);
    _.intest($b.str('b'), _.l);
    _.intest(99, _.l);
    _.intest(0, _.l);
    _.intest($b.str('z'), _.l);
    _.intest($b.str('c'), _.l);
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/lists/in.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

