/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/lists/map.py

load("build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/lists/map.py', function (_) {
    _.__doc__ = "";
    _.foo = $def(function $_foo(x) { // 2
        return $b.mult(x, x);
    });
    _.foo.__module__ = _.__name__;
    _.foo.__name__ = $b.str("foo");
    _.y = $b.list([1, 2, 3, 4, 5]);
    _.z = $b.map(_.foo, _.y);
    var __pjs_iter_1 = $b.foriter(_.z);
    while (__pjs_iter_1.trynext()) {
        _.val = __pjs_iter_1.value;
    
        $b.print(_.val);//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/lists/map.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

