/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/lists/subclass2.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/lists/subclass2.py', function (_) {
    _.__doc__ = "";
    _.List = Class('List', [$b.object], (function(){
        var __1 = {};
        __1.__init__ = $def({'l': $b.list([])}, function $___init__(self, l) { // 3
            self._list = $b.list(l);
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        __1.append = $def(function $_append(self, x) { // 6
            self._list.append(x);
        });
        __1.append.__module__ = _.__name__;
        __1.append.__name__ = $b.str("append");
        __1.remove = $def(function $_remove(self, x) { // 9
            self._list.remove(x);
        });
        __1.remove.__module__ = _.__name__;
        __1.remove.__name__ = $b.str("remove");
        __1.__str__ = $def(function $___str__(self) { // 12
            return $b.str(self._list);
        });
        __1.__str__.__module__ = _.__name__;
        __1.__str__.__name__ = $b.str("__str__");
        return __1;
    }()));
    _.List.__module__ = _.__name__;
    _.A = Class('A', [_.List], (function(){
        var __1 = {};
        __1.my_append = $def(function $_my_append(self, a) { // 17
            self.append(a);
        });
        __1.my_append.__module__ = _.__name__;
        __1.my_append.__name__ = $b.str("my_append");
        return __1;
    }()));
    _.A.__module__ = _.__name__;
    _.a = _.A();
    $b.print(_.a);//, true
    _.a.append(5);
    $b.print(_.a);//, true
    _.a.append(6);
    $b.print(_.a);//, true
    _.a.remove(5);
    $b.print(_.a);//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/lists/subclass2.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

