/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/browser/jqueryui.py

module('/home/jared/clone/pjs/test/browser/jqueryui.py', function (_) {
    _.__doc__ = "";
    _.SplitPane = Class('SplitPane', [], (function(){
        var __1 = {};
        __1.__init__ = $m(function (self, node) {
            self.node = node;
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = "__init__";
        return __1;
    }()));
    _.SplitPane.__module__ = _.__name__;
    $b.str('Ways of embedding javascript code...\n' +
    '\n' +
    'prepend js. to everything.... the js. gets removed...\n' +
    '\n' +
    'so\n' +
    '\n' +
    'hello(js.jQuery(\'world\'))\n' +
    '\n' +
    'becomes\n' +
    '\n' +
    'hello(jQuery($b.js($b.str(\'world\'))))\n' +
    '\n' +
    '');
    _.json = $b.__import__("json", _.__name__, _.__file__);
    _.jq = window.jQuery;
    _.onload = $m(function (jQuery) {
        _.jq($b.js($b.str('#tabs'))).tabs();
        $b.print(_.jq($b.js($b.str('#tabs'))).length);//, true
        $b.print(_.json.dumps($b.list([$b.str('hello'), $b.str('man'), $b.dict([[$b.str('yeah'), 6], [5, 2]])])));//, true
    });
    _.onload.__module__ = _.__name__;
    _.onload.__name__ = "onload";
    if ($b.bool($b.do_ops(_.__name__, '==', $b.str('__main__'))) === true) {
        _.jq($b.js($b.str('document'))).ready(_.onload);
    }
});

module('/home/jared/clone/pjs/test/browser/json.py', function (_) {
    _.__doc__ = "";
    _.loads = $m(function (string) {
        return window.JSON.parse($b.js(string));
    });
    _.loads.__module__ = _.__name__;
    _.loads.__name__ = "loads";
    _.dumps = $m(function (obj) {
        return window.JSON.stringify($b.js(obj));
    });
    _.dumps.__module__ = _.__name__;
    _.dumps.__name__ = "dumps";
});

__builtins__.run_main('/home/jared/clone/pjs/test/browser/jqueryui.py');
