/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/algorithms/sqrt.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/algorithms/sqrt.py', function (_) {
    _.__doc__ = "";
    _.abs = $def(function $_abs(x) { // 1
        if ($b.bool($b.do_ops(x, '>', 0)) === true) {
            return x;
        } else return -x;
    });
    _.abs.__module__ = _.__name__;
    _.abs.__name__ = $b.str("abs");
    _.sqrt = $def(function $_sqrt(x) { // 7
        var eps = $b._float(0.000000);
        x = $b._float(x);
        var r = $b.div(x, 2);
        var residual = $b.sub($b.pow(r, 2), x);
        while ($b.bool($b.do_ops(_.abs(residual), '>', eps)) === true) {
            var r_d = $b.div(-residual, $b.mult(2, r));
            r = $b.add(r, r_d);
            residual = $b.sub($b.pow(r, 2), x);
        }
        return r;
    });
    _.sqrt.__module__ = _.__name__;
    _.sqrt.__name__ = $b.str("sqrt");
    _.p = $def(function $_p(x) { // 18
        var prec = 11;
        var l = $b.list($b.iter($b.str(x))).__getslice__(0, prec);
        if ($b.bool(!$b.bool($b.do_ops($b.str('.'), 'in', l))) === true) {
            l.append($b.str('.'));
            l.append($b.str('0'));
        }
        while ($b.bool($b.do_ops($b.len(l), '<', prec)) === true) {
            l.append($b.str('0'));
        }
        var s = $b.str('');
        var __pjs_iter0 = $b.foriter(l);
        while (__pjs_iter0.trynext()) {
            var c = __pjs_iter0.value;
        
            s = $b.add(s, c);
        }
        return s;
    });
    _.p.__module__ = _.__name__;
    _.p.__name__ = $b.str("p");
    $b.print(_.p(_.sqrt(1)));//, true
    $b.print(_.p(_.sqrt(2)));//, true
    $b.print(_.p(_.sqrt(3)));//, true
    $b.print(_.p(_.sqrt(4)));//, true
    $b.print(_.p(_.sqrt(5)));//, true
    $b.print(_.p(_.sqrt(6)));//, true
    $b.print(_.p(_.sqrt(7000)));//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/algorithms/sqrt.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

