/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/libraries/xmlwriter.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/libraries/xmlwriter.py', function (_) {
    _.__doc__ = "";
    _.StringWriter = Class('StringWriter', [$b.object], (function(){
        var __1 = {};
        __1.__init__ = $def(function $___init__(self) { // 4
            self.contents = $b.str('');
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        __1.write = $def(function $_write(self, text) { // 7
            self.contents = $b.add(self.contents, text);
        });
        __1.write.__module__ = _.__name__;
        __1.write.__name__ = $b.str("write");
        __1.getContents = $def(function $_getContents(self) { // 10
            return self.contents;
        });
        __1.getContents.__module__ = _.__name__;
        __1.getContents.__name__ = $b.str("getContents");
        return __1;
    }()));
    _.StringWriter.__module__ = _.__name__;
    _.XmlWriter = Class('XmlWriter', [$b.object], (function(){
        var __1 = {};
        __1.Node = Class('Node', [$b.object], (function(){
            var __2 = {};
            __2.__init__ = $def(function $___init__(self) { // 17
                
            });
            __2.__init__.__module__ = _.__name__;
            __2.__init__.__name__ = $b.str("__init__");
            return __2;
        }()));
        __1.Node.__module__ = _.__name__;
        __1.TextNode = Class('TextNode', [__1.Node], (function(){
            var __2 = {};
            __2.__init__ = $def(function $___init__(self, text) { // 22
                self.text = text;
            });
            __2.__init__.__module__ = _.__name__;
            __2.__init__.__name__ = $b.str("__init__");
            __2.write = $def(function $_write(self, writer, indent) { // 25
                writer.write(self.text);
            });
            __2.write.__module__ = _.__name__;
            __2.write.__name__ = $b.str("write");
            return __2;
        }()));
        __1.TextNode.__module__ = _.__name__;
        __1.Element = Class('Element', [__1.Node], (function(){
            var __2 = {};
            __2.__init__ = $def(function $___init__(self, tag) { // 30
                self.tag = tag;
                self.children = $b.list([]);
                self.attributes = $b.dict([]);
                self.hastext = $b.False;
            });
            __2.__init__.__module__ = _.__name__;
            __2.__init__.__name__ = $b.str("__init__");
            __2.addElement = $def(function $_addElement(self, tag) { // 36
                var child = _.XmlWriter.Element(tag);
                self.children.append(child);
                return child;
            });
            __2.addElement.__module__ = _.__name__;
            __2.addElement.__name__ = $b.str("addElement");
            __2.addTextNode = $def(function $_addTextNode(self, text) { // 41
                var child = _.XmlWriter.TextNode(text);
                self.children.append(child);
                self.hastext = $b.True;
                return child;
            });
            __2.addTextNode.__module__ = _.__name__;
            __2.addTextNode.__name__ = $b.str("addTextNode");
            __2.addAttribute = $def(function $_addAttribute(self, name, value) { // 47
                self.attributes.__setitem__(name, value);
            });
            __2.addAttribute.__module__ = _.__name__;
            __2.addAttribute.__name__ = $b.str("addAttribute");
            __2.write = $def(function $_write(self, writer, indent) { // 50
                if ($b.bool($b.do_ops(indent, '>', 0)) === true) {
                    _.XmlWriter.indent(writer, indent);
                }
                writer.write($b.add($b.str('<'), self.tag));
                var __pjs_iter0 = $b.foriter(self.attributes);
                while (__pjs_iter0.trynext()) {
                    var k = __pjs_iter0.value;
                
                    writer.write($b.add($b.add($b.add($b.add($b.str(' '), k), $b.str('="')), self.attributes.__getitem__(k)), $b.str('"')));
                }
                if ($b.bool($b.do_ops($b.len(self.children), '==', 0)) === true) {
                    writer.write($b.str(' />'));
                    return;
                }
                writer.write($b.str('>'));
                var __pjs_iter0 = $b.foriter(self.children);
                while (__pjs_iter0.trynext()) {
                    var c = __pjs_iter0.value;
                
                    c.write(writer, $b.add(indent, 1));
                }
                if ($b.bool(!$b.bool(self.hastext)) === true) {
                    _.XmlWriter.indent(writer, indent);
                }
                writer.write($b.add($b.add($b.str('</'), self.tag), $b.str('>')));
            });
            __2.write.__module__ = _.__name__;
            __2.write.__name__ = $b.str("write");
            return __2;
        }()));
        __1.Element.__module__ = _.__name__;
        __1.indent = $b.staticmethod($def(function $_indent(writer, indent) { // 66
            writer.write($b.str('\n' +
            ''));
            var __pjs_iter0 = $b.foriter($b.xrange(0, indent));
            while (__pjs_iter0.trynext()) {
                var x = __pjs_iter0.value;
            
                writer.write($b.str('  '));
            }
        }));
        __1.indent.__module__ = _.__name__;
        __1.indent.__name__ = $b.str("indent");
        __1.createRoot = $def(function $_createRoot(self, tag) { // 72
            self.root = self.Element(tag);
            return self.root;
        });
        __1.createRoot.__module__ = _.__name__;
        __1.createRoot.__name__ = $b.str("createRoot");
        __1.write = $def(function $_write(self, writer) { // 76
            self.root.write(writer, 0);
        });
        __1.write.__module__ = _.__name__;
        __1.write.__name__ = $b.str("write");
        return __1;
    }()));
    _.XmlWriter.__module__ = _.__name__;
    if ($b.bool($b.do_ops(_.__name__, '==', $b.str('__main__'))) === true) {
        _.w = _.XmlWriter();
        _.r = _.w.createRoot($b.str('foo'));
        _.r1 = _.r.addElement($b.str('r1'));
        _.r1.addAttribute($b.str('spam'), $b.str('eggs'));
        _.r2 = _.r1.addElement($b.str('r2'));
        _.r2.addAttribute($b.str('eggs'), $b.str('spam'));
        _.r2.addTextNode($b.str('This is some text'));
        _.s = _.StringWriter();
        _.w.write(_.s);
        $b.print(_.s.getContents());//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/libraries/xmlwriter.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

