/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /Users/jared/clone/PJs/test/py2js/functions/floatdiv.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/__future__.py', function (_) {
    _.__doc__ = 'Record of phased-in incompatible language changes.\n' +
'\n' +
'Each line is of the form:\n' +
'\n' +
'    FeatureName = "_Feature(" OptionalRelease "," MandatoryRelease ","\n' +
'                              CompilerFlag ")"\n' +
'\n' +
'where, normally, OptionalRelease < MandatoryRelease, and both are 5-tuples\n' +
'of the same form as sys.version_info:\n' +
'\n' +
'    (PY_MAJOR_VERSION, # the 2 in 2.1.0a3; an int\n' +
'     PY_MINOR_VERSION, # the 1; an int\n' +
'     PY_MICRO_VERSION, # the 0; an int\n' +
'     PY_RELEASE_LEVEL, # "alpha", "beta", "candidate" or "final"; string\n' +
'     PY_RELEASE_SERIAL # the 3; an int\n' +
'    )\n' +
'\n' +
'OptionalRelease records the first release in which\n' +
'\n' +
'    from __future__ import FeatureName\n' +
'\n' +
'was accepted.\n' +
'\n' +
'In the case of MandatoryReleases that have not yet occurred,\n' +
'MandatoryRelease predicts the release in which the feature will become part\n' +
'of the language.\n' +
'\n' +
'Else MandatoryRelease records when the feature became part of the language;\n' +
'in releases at or after that, modules no longer need\n' +
'\n' +
'    from __future__ import FeatureName\n' +
'\n' +
'to use the feature in question, but may continue to use such imports.\n' +
'\n' +
'MandatoryRelease may also be None, meaning that a planned feature got\n' +
'dropped.\n' +
'\n' +
'Instances of class _Feature have two corresponding methods,\n' +
'.getOptionalRelease() and .getMandatoryRelease().\n' +
'\n' +
'CompilerFlag is the (bitfield) flag that should be passed in the fourth\n' +
'argument to the builtin function compile() to enable the feature in\n' +
'dynamically compiled code.  This flag is stored in the .compiler_flag\n' +
'attribute on _Future instances.  These values must match the appropriate\n' +
'#defines of CO_xxx flags in Include/compile.h.\n' +
'\n' +
'No feature line is ever to be deleted from this file.';
    $b.str('Record of phased-in incompatible language changes.\n' +
    '\n' +
    'Each line is of the form:\n' +
    '\n' +
    '    FeatureName = "_Feature(" OptionalRelease "," MandatoryRelease ","\n' +
    '                              CompilerFlag ")"\n' +
    '\n' +
    'where, normally, OptionalRelease < MandatoryRelease, and both are 5-tuples\n' +
    'of the same form as sys.version_info:\n' +
    '\n' +
    '    (PY_MAJOR_VERSION, # the 2 in 2.1.0a3; an int\n' +
    '     PY_MINOR_VERSION, # the 1; an int\n' +
    '     PY_MICRO_VERSION, # the 0; an int\n' +
    '     PY_RELEASE_LEVEL, # "alpha", "beta", "candidate" or "final"; string\n' +
    '     PY_RELEASE_SERIAL # the 3; an int\n' +
    '    )\n' +
    '\n' +
    'OptionalRelease records the first release in which\n' +
    '\n' +
    '    from __future__ import FeatureName\n' +
    '\n' +
    'was accepted.\n' +
    '\n' +
    'In the case of MandatoryReleases that have not yet occurred,\n' +
    'MandatoryRelease predicts the release in which the feature will become part\n' +
    'of the language.\n' +
    '\n' +
    'Else MandatoryRelease records when the feature became part of the language;\n' +
    'in releases at or after that, modules no longer need\n' +
    '\n' +
    '    from __future__ import FeatureName\n' +
    '\n' +
    'to use the feature in question, but may continue to use such imports.\n' +
    '\n' +
    'MandatoryRelease may also be None, meaning that a planned feature got\n' +
    'dropped.\n' +
    '\n' +
    'Instances of class _Feature have two corresponding methods,\n' +
    '.getOptionalRelease() and .getMandatoryRelease().\n' +
    '\n' +
    'CompilerFlag is the (bitfield) flag that should be passed in the fourth\n' +
    'argument to the builtin function compile() to enable the feature in\n' +
    'dynamically compiled code.  This flag is stored in the .compiler_flag\n' +
    'attribute on _Future instances.  These values must match the appropriate\n' +
    '#defines of CO_xxx flags in Include/compile.h.\n' +
    '\n' +
    'No feature line is ever to be deleted from this file.\n' +
    '');
    _.all_feature_names = $b.list([$b.str('nested_scopes'), $b.str('generators'), $b.str('division'), $b.str('absolute_import'), $b.str('with_statement'), $b.str('print_function'), $b.str('unicode_literals')]);
    _.__all__ = $b.add($b.list([$b.str('all_feature_names')]), _.all_feature_names);
    _.CO_NESTED = 16;
    _.CO_GENERATOR_ALLOWED = 0;
    _.CO_FUTURE_DIVISION = 8192;
    _.CO_FUTURE_ABSOLUTE_IMPORT = 16384;
    _.CO_FUTURE_WITH_STATEMENT = 32768;
    _.CO_FUTURE_PRINT_FUNCTION = 65536;
    _.CO_FUTURE_UNICODE_LITERALS = 131072;
    _._Feature = Class('_Feature', [], (function(){
        var __0 = {};
        __0.__init__ = $def(function $___init__(self, optionalRelease, mandatoryRelease, compiler_flag) { // 75
            self.optional = optionalRelease;
            self.mandatory = mandatoryRelease;
            self.compiler_flag = compiler_flag;
        });
        __0.__init__.__module__ = _.__name__;
        __0.__init__.__name__ = $b.str("__init__");
        __0.getOptionalRelease = $def(function $_getOptionalRelease(self) { // 80
            $b.str('Return first release in which this feature was recognized.\n' +
            '\n' +
            '        This is a 5-tuple, of the same form as sys.version_info.\n' +
            '        ');
            return self.optional;
        });
        __0.getOptionalRelease.__module__ = _.__name__;
        __0.getOptionalRelease.__name__ = $b.str("getOptionalRelease");
        __0.getMandatoryRelease = $def(function $_getMandatoryRelease(self) { // 88
            $b.str('Return release in which this feature will become mandatory.\n' +
            '\n' +
            '        This is a 5-tuple, of the same form as sys.version_info, or, if\n' +
            '        the feature was dropped, is None.\n' +
            '        ');
            return self.mandatory;
        });
        __0.getMandatoryRelease.__module__ = _.__name__;
        __0.getMandatoryRelease.__name__ = $b.str("getMandatoryRelease");
        __0.__repr__ = $def(function $___repr__(self) { // 97
            return $b.add($b.str('_Feature'), $b.repr($b.tuple([self.optional, self.mandatory, self.compiler_flag])));
        });
        __0.__repr__.__module__ = _.__name__;
        __0.__repr__.__name__ = $b.str("__repr__");
        return __0;
    }()));
    _._Feature.__module__ = _.__name__;
    _.nested_scopes = _._Feature($b.tuple([2, 1, 0, $b.str('beta'), 1]), $b.tuple([2, 2, 0, $b.str('alpha'), 0]), _.CO_NESTED);
    _.generators = _._Feature($b.tuple([2, 2, 0, $b.str('alpha'), 1]), $b.tuple([2, 3, 0, $b.str('final'), 0]), _.CO_GENERATOR_ALLOWED);
    _.division = _._Feature($b.tuple([2, 2, 0, $b.str('alpha'), 2]), $b.tuple([3, 0, 0, $b.str('alpha'), 0]), _.CO_FUTURE_DIVISION);
    _.absolute_import = _._Feature($b.tuple([2, 5, 0, $b.str('alpha'), 1]), $b.tuple([2, 7, 0, $b.str('alpha'), 0]), _.CO_FUTURE_ABSOLUTE_IMPORT);
    _.with_statement = _._Feature($b.tuple([2, 5, 0, $b.str('alpha'), 1]), $b.tuple([2, 6, 0, $b.str('alpha'), 0]), _.CO_FUTURE_WITH_STATEMENT);
    _.print_function = _._Feature($b.tuple([2, 6, 0, $b.str('alpha'), 2]), $b.tuple([3, 0, 0, $b.str('alpha'), 0]), _.CO_FUTURE_PRINT_FUNCTION);
    _.unicode_literals = _._Feature($b.tuple([2, 6, 0, $b.str('alpha'), 2]), $b.tuple([3, 0, 0, $b.str('alpha'), 0]), _.CO_FUTURE_UNICODE_LITERALS);
});

module('/Users/jared/clone/PJs/test/py2js/functions/floatdiv.py', function (_) {
    _.__doc__ = "";
    var __pjs_tmp_module = $b.__import__("__future__", _.__name__, _.__file__);
    _.division = __pjs_tmp_module.division;
    _.a = 3;
    _.b = 2;
    _.c = $b.div(_.a, _.b);
    $b.print(_.c);//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/Users/jared/clone/PJs/test/py2js/functions/floatdiv.py', ['/Users/jared/clone/PJs', '/Users/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/pip-1.3-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg', '/Users/jared/.venv/default/lib/python27.zip', '/Users/jared/.venv/default/lib/python2.7', '/Users/jared/.venv/default/lib/python2.7/plat-darwin', '/Users/jared/.venv/default/lib/python2.7/plat-mac', '/Users/jared/.venv/default/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/Extras/lib/python', '/Users/jared/.venv/default/lib/python2.7/lib-tk', '/Users/jared/.venv/default/lib/python2.7/lib-old', '/Users/jared/.venv/default/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/lib/python2.7/site-packages']);

