/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/functions/isinstance.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/functions/isinstance.py', function (_) {
    _.__doc__ = "";
    _.Spam = Class('Spam', [$b.object], (function(){
        var __1 = {};
        __1.__init__ = $def(function $___init__(self, value) { // 4
            self.value = value;
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        return __1;
    }()));
    _.Spam.__module__ = _.__name__;
    _.Eggs = Class('Eggs', [$b.object], (function(){
        var __1 = {};
        __1.__init__ = $def(function $___init__(self, value) { // 9
            self.value = value;
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        return __1;
    }()));
    _.Eggs.__module__ = _.__name__;
    _.s = _.Spam(1);
    _.e = _.Eggs(2);
    if ($b.bool($b.isinstance(_.s, _.Spam)) === true) {
        $b.print($b.str('s is Spam - correct'));//, true
    }
    if ($b.bool($b.isinstance(_.s, _.Eggs)) === true) {
        $b.print($b.str('s is Eggs - incorrect'));//, true
    }
    if ($b.bool($b.isinstance(_.e, _.Spam)) === true) {
        $b.print($b.str('e is Spam - incorrect'));//, true
    }
    if ($b.bool($b.isinstance(_.e, _.Eggs)) === true) {
        $b.print($b.str('e is Eggs - correct'));//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/functions/isinstance.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

