/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /Users/jared/clone/PJs/test/py2js/functions/isinstance.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/Users/jared/clone/PJs/test/py2js/functions/isinstance.py', function (_) {
    _.__doc__ = "";
    _.Spam = Class('Spam', [$b.object], (function(){
        var __0 = {};
        __0.__init__ = $def(function $___init__(self, value) { // 4
            self.value = value;
        });
        __0.__init__.__module__ = _.__name__;
        __0.__init__.__name__ = $b.str("__init__");
        return __0;
    }()));
    _.Spam.__module__ = _.__name__;
    _.Eggs = Class('Eggs', [$b.object], (function(){
        var __0 = {};
        __0.__init__ = $def(function $___init__(self, value) { // 9
            self.value = value;
        });
        __0.__init__.__module__ = _.__name__;
        __0.__init__.__name__ = $b.str("__init__");
        return __0;
    }()));
    _.Eggs.__module__ = _.__name__;
    _.s = _.Spam(1);
    _.e = _.Eggs(2);
    if ($b.bool($b.isinstance(_.s, _.Spam)) === true) {
        $b.print($b.str('s is Spam - correct'));//, true
    }
    if ($b.bool($b.isinstance(_.s, _.Eggs)) === true) {
        $b.print($b.str('s is Eggs - incorrect'));//, true
    }
    if ($b.bool($b.isinstance(_.e, _.Spam)) === true) {
        $b.print($b.str('e is Spam - incorrect'));//, true
    }
    if ($b.bool($b.isinstance(_.e, _.Eggs)) === true) {
        $b.print($b.str('e is Eggs - correct'));//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/Users/jared/clone/PJs/test/py2js/functions/isinstance.py', ['/Users/jared/clone/PJs', '/Users/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/pip-1.3-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg', '/Users/jared/.venv/default/lib/python27.zip', '/Users/jared/.venv/default/lib/python2.7', '/Users/jared/.venv/default/lib/python2.7/plat-darwin', '/Users/jared/.venv/default/lib/python2.7/plat-mac', '/Users/jared/.venv/default/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/Extras/lib/python', '/Users/jared/.venv/default/lib/python2.7/lib-tk', '/Users/jared/.venv/default/lib/python2.7/lib-old', '/Users/jared/.venv/default/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/lib/python2.7/site-packages']);

