/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/functions/ne.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/functions/ne.py', function (_) {
    _.__doc__ = "";
    var __pjs_iter0 = $b.foriter($b.list([$b.tuple([1, 2]), $b.tuple([$b.str('aaa'), $b.str('bbb')]), $b.tuple([4, 4]), $b.tuple([$b.str('a'), $b.str('a')])]));
    while (__pjs_iter0.trynext()) {
        _.x = __pjs_iter0.value.__getitem__(0);
        _.y = __pjs_iter0.value.__getitem__(1);
        
        if ($b.bool($b.do_ops(_.x, '!=', _.y)) === true) {
            $b.print($b.add($b.add($b.str(_.x), $b.str(' <> ')), $b.str(_.y)));//, true
        } else $b.print($b.add($b.add($b.add($b.str('not: '), $b.str(_.x)), $b.str(' <> ')), $b.str(_.y)));//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/functions/ne.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

