/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /Users/jared/clone/PJs/test/py2js/functions/or.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/Users/jared/clone/PJs/test/py2js/functions/or.py', function (_) {
    _.__doc__ = "";
    _.tests = $b.list([$b.tuple([$b.False, $b.False]), $b.tuple([$b.False, $b.True]), $b.tuple([$b.True, $b.False]), $b.tuple([$b.True, $b.True]), $b.tuple([$b.True, $b.None]), $b.tuple([$b.False, $b.None]), $b.tuple([$b.None, $b.True]), $b.tuple([$b.None, $b.False])]);
    _.pp = $def(function $_pp(v) { // 4
        if ($b.bool($b.do_ops(v, '==', $b.False)) === true) {
            return $b.str('F');
        }
        if ($b.bool($b.do_ops(v, '==', $b.True)) === true) {
            return $b.str('T');
        }
        return $b.str('?');
    });
    _.pp.__module__ = _.__name__;
    _.pp.__name__ = $b.str("pp");
    var __pjs_iter_1 = $b.foriter(_.tests);
    while (__pjs_iter_1.trynext()) {
        _.t = __pjs_iter_1.value;
    
        var __pjs_tmp = _.t;
        _.b1 = __pjs_tmp.__getitem__(0);
        _.b2 = __pjs_tmp.__getitem__(1);
        $b.print($b.add($b.add($b.add($b.add(_.pp(_.b1), $b.str(' OR ')), _.pp(_.b2)), $b.str('=')), _.pp($b.bool(_.b1) || $b.bool(_.b2))));//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/Users/jared/clone/PJs/test/py2js/functions/or.py', ['/Users/jared/clone/PJs', '/Users/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/pip-1.3-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg', '/Users/jared/.venv/default/lib/python27.zip', '/Users/jared/.venv/default/lib/python2.7', '/Users/jared/.venv/default/lib/python2.7/plat-darwin', '/Users/jared/.venv/default/lib/python2.7/plat-mac', '/Users/jared/.venv/default/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/Extras/lib/python', '/Users/jared/.venv/default/lib/python2.7/lib-tk', '/Users/jared/.venv/default/lib/python2.7/lib-old', '/Users/jared/.venv/default/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/lib/python2.7/site-packages']);

