/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/functions/or.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/functions/or.py', function (_) {
    _.__doc__ = "";
    _.tests = $b.list([$b.tuple([$b.False, $b.False]), $b.tuple([$b.False, $b.True]), $b.tuple([$b.True, $b.False]), $b.tuple([$b.True, $b.True]), $b.tuple([$b.True, $b.None]), $b.tuple([$b.False, $b.None]), $b.tuple([$b.None, $b.True]), $b.tuple([$b.None, $b.False])]);
    _.pp = $def(function $_pp(v) { // 4
        if ($b.bool($b.do_ops(v, '==', $b.False)) === true) {
            return $b.str('F');
        }
        if ($b.bool($b.do_ops(v, '==', $b.True)) === true) {
            return $b.str('T');
        }
        return $b.str('?');
    });
    _.pp.__module__ = _.__name__;
    _.pp.__name__ = $b.str("pp");
    var __pjs_iter0 = $b.foriter(_.tests);
    while (__pjs_iter0.trynext()) {
        _.t = __pjs_iter0.value;
    
        var __pjs_tmp = _.t;
        _.b1 = __pjs_tmp.__getitem__(0);
        _.b2 = __pjs_tmp.__getitem__(1);
        $b.print($b.add($b.add($b.add($b.add(_.pp(_.b1), $b.str(' OR ')), _.pp(_.b2)), $b.str('=')), _.pp($b.bool(_.b1) || $b.bool(_.b2))));//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/functions/or.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

