/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/functions/sort_cmp.py

load("build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/home/jared/clone/pjs/test/py2js/functions/sort_cmp.py', function (_) {
    _.__doc__ = "";
    _.revcmp = $def(function $_revcmp(a, b) { // 2
        if ($b.bool($b.do_ops(b, '<', a)) === true) {
            return -1;
        }
        if ($b.bool($b.do_ops(b, '==', a)) === true) {
            return 0;
        }
        return 1;
    });
    _.revcmp.__module__ = _.__name__;
    _.revcmp.__name__ = $b.str("revcmp");
    _.l = $b.list([4, 7, 2, 3, 8, 1, 3]);
    _.l.sort(_.revcmp);
    $b.print(_.l.__getitem__(0));//, true
    $b.print(_.l.__getitem__(1));//, true
    $b.print(_.l.__getitem__(2));//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/home/jared/clone/pjs/test/py2js/functions/sort_cmp.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/jared/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']);

