/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /Users/jared/clone/PJs/test/py2js/functions/sort_cmp.py

load("pjs/data/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
var window  = this;
module('/Users/jared/clone/PJs/test/py2js/functions/sort_cmp.py', function (_) {
    _.__doc__ = "";
    _.revcmp = $def(function $_revcmp(a, b) { // 2
        if ($b.bool($b.do_ops(b, '<', a)) === true) {
            return -1;
        }
        if ($b.bool($b.do_ops(b, '==', a)) === true) {
            return 0;
        }
        return 1;
    });
    _.revcmp.__module__ = _.__name__;
    _.revcmp.__name__ = $b.str("revcmp");
    _.l = $b.list([4, 7, 2, 3, 8, 1, 3]);
    _.l.sort(_.revcmp);
    $b.print(_.l.__getitem__(0));//, true
    $b.print(_.l.__getitem__(1));//, true
    $b.print(_.l.__getitem__(2));//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
var pjs_main = __builtins__.run_main('/Users/jared/clone/PJs/test/py2js/functions/sort_cmp.py', ['/Users/jared/clone/PJs', '/Users/jared/.venv/default/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/pip-1.3-py2.7.egg', '/Users/jared/.venv/default/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg', '/Users/jared/.venv/default/lib/python27.zip', '/Users/jared/.venv/default/lib/python2.7', '/Users/jared/.venv/default/lib/python2.7/plat-darwin', '/Users/jared/.venv/default/lib/python2.7/plat-mac', '/Users/jared/.venv/default/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/Extras/lib/python', '/Users/jared/.venv/default/lib/python2.7/lib-tk', '/Users/jared/.venv/default/lib/python2.7/lib-old', '/Users/jared/.venv/default/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/jared/.venv/default/lib/python2.7/site-packages']);

