/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file %(file)s

load("%(lib)s");
var console = {log:function(){print.apply(this, arguments);}};
%(text)s
__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('%(file)s', %(path)s);

