/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/modules/classname.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/modules/classname.py', function (_) {
    _.__doc__ = "";
    var __pjs_tmp_module = $b.__import__("modules.moda", _.__name__, _.__file__);
    _.ModA = __pjs_tmp_module.moda.ModA;
    _.m = _.ModA($b.str('hello'));
    _.m.describe();
    _.mc = _.m.clone();
    _.mc.describe();
});

module('/home/jared/clone/pjs/test/py2js/modules/modules/moda.py', function (_) {
    _.__doc__ = "";
    _.ModA = Class('ModA', [], (function(){
        var __1 = {};
        __1.__init__ = $def(function $___init__(self, val) { // 5
            self.val = val;
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        __1.clone = $def(function $_clone(self) { // 8
            return _.ModA(self.val);
        });
        __1.clone.__module__ = _.__name__;
        __1.clone.__name__ = $b.str("clone");
        __1.describe = $def(function $_describe(self) { // 11
            $b.print(self.val);//, true
        });
        __1.describe.__module__ = _.__name__;
        __1.describe.__name__ = $b.str("describe");
        return __1;
    }()));
    _.ModA.__module__ = _.__name__;
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/modules/classname.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

