/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/modules/import_multi.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/modules/import_multi.py', function (_) {
    _.__doc__ = "";
    _.imported = $b.__import__("imported.modulec", _.__name__, _.__file__);
    _.foo = $def(function $_foo() { // 4
        $b.print($b.str('foo'));//, true
        _.imported.modulec.foo();
    });
    _.foo.__module__ = _.__name__;
    _.foo.__name__ = $b.str("foo");
    _.foo();
});

module('/home/jared/clone/pjs/test/py2js/modules/imported/modulec.py', function (_) {
    _.__doc__ = "";
    _.submodules = $b.__import__("submodules.submodulea", _.__name__, _.__file__);
    _.foo = $def(function $_foo() { // 4
        $b.print($b.str('imported.modulec.foo()'));//, true
        _.submodules.submodulea.foo();
    });
    _.foo.__module__ = _.__name__;
    _.foo.__name__ = $b.str("foo");
});

module('/home/jared/clone/pjs/test/py2js/modules/imported/submodules/submodulea.py', function (_) {
    _.__doc__ = "";
    _.foo = $def(function $_foo() { // 2
        $b.print($b.str('imported.modules.submodules.modulea.foo()'));//, true
    });
    _.foo.__module__ = _.__name__;
    _.foo.__name__ = $b.str("foo");
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/modules/import_multi.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

