/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/modules/import_diamond.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/modules/import_diamond.py', function (_) {
    _.__doc__ = "";
    _.modules = $b.__import__("modules.diamond1", _.__name__, _.__file__);
    _.modules = $b.__import__("modules.diamond2", _.__name__, _.__file__);
    _.modules.diamond1.run();
    _.modules.diamond2.run();
});

module('/home/jared/clone/pjs/test/py2js/modules/modules/diamond1.py', function (_) {
    _.__doc__ = "";
    _.submodules = $b.__import__("submodules.diamondbase", _.__name__, _.__file__);
    _.run = $def(function $_run() { // 4
        $b.print($b.str('calling diamond1.run()'));//, true
        _.submodules.diamondbase.run();
    });
    _.run.__module__ = _.__name__;
    _.run.__name__ = $b.str("run");
});

module('/home/jared/clone/pjs/test/py2js/modules/modules/diamond2.py', function (_) {
    _.__doc__ = "";
    _.submodules = $b.__import__("submodules.diamondbase", _.__name__, _.__file__);
    _.run = $def(function $_run() { // 4
        $b.print($b.str('Calling diamond2.run()'));//, true
        _.submodules.diamondbase.run();
    });
    _.run.__module__ = _.__name__;
    _.run.__name__ = $b.str("run");
});

module('/home/jared/clone/pjs/test/py2js/modules/modules/submodules/diamondbase.py', function (_) {
    _.__doc__ = "";
    _.counter = 0;
    _.run = $def(function $_run() { // 4
        // switching to global scope: counter
        _.counter = $b.add(_.counter, 1);
        $b.print($b.add($b.add($b.str('diamondbase called '), $b.str(_.counter)), $b.str(' time(s)')));//, true
    });
    _.run.__module__ = _.__name__;
    _.run.__name__ = $b.str("run");
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/modules/import_diamond.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

