/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/modules/import_alias.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/modules/import_alias.py', function (_) {
    _.__doc__ = "";
    var __pjs_tmp_module = $b.__import__("imported.alias_fns", _.__name__, _.__file__);
    _.bar = __pjs_tmp_module.alias_fns.foo;
    var __pjs_tmp_module = $b.__import__("imported.alias_classes", _.__name__, _.__file__);
    _.eggs = __pjs_tmp_module.alias_classes.spam;
    _.bar();
    _.e = _.eggs();
    _.e.msg();
});

module('/home/jared/clone/pjs/test/py2js/modules/imported/alias_classes.py', function (_) {
    _.__doc__ = "";
    _.spam = Class('spam', [], (function(){
        var __1 = {};
        __1.__init__ = $def(function $___init__(self) { // 4
            self.msgtxt = $b.str('this is spam');
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        __1.msg = $def(function $_msg(self) { // 7
            $b.print(self.msgtxt);//, true
        });
        __1.msg.__module__ = _.__name__;
        __1.msg.__name__ = $b.str("msg");
        return __1;
    }()));
    _.spam.__module__ = _.__name__;
    if ($b.bool($b.do_ops(_.__name__, '==', $b.str('__main__'))) === true) {
        _.s = _.spam();
        _.s.msg();
    }
});

module('/home/jared/clone/pjs/test/py2js/modules/imported/alias_fns.py', function (_) {
    _.__doc__ = "";
    _.foo = $def(function $_foo() { // 2
        $b.print($b.str('this is foo'));//, true
    });
    _.foo.__module__ = _.__name__;
    _.foo.__name__ = $b.str("foo");
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/modules/import_alias.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

