/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/modules/module_name.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/modules/module_name.py', function (_) {
    _.__doc__ = "";
    _.modules = $b.__import__("modules.module_name", _.__name__, _.__file__);
    $b.print($b.add($b.str('1st level module __name__:'), _.__name__));//, true
});

module('/home/jared/clone/pjs/test/py2js/modules/modules/module_name.py', function (_) {
    _.__doc__ = "";
    _.submodules = $b.__import__("submodules.module_name", _.__name__, _.__file__);
    $b.print($b.add($b.str('2nd level module __name__:'), _.__name__));//, true
});

module('/home/jared/clone/pjs/test/py2js/modules/modules/submodules/module_name.py', function (_) {
    _.__doc__ = "";
    $b.print($b.add($b.str('3rd level module __name__:'), _.__name__));//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/modules/module_name.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

