/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/basic/for_in.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/basic/for_in.py', function (_) {
    _.__doc__ = "";
    _.a = $b.list([1, 2, 3, 4, 5]);
    var __pjs_iter0 = $b.foriter(_.a);
    while (__pjs_iter0.trynext()) {
        _.x = __pjs_iter0.value;
    
        $b.print(_.x);//, true
    }
    _.a = $b.tuple([$b.str('cats'), $b.str('dogs'), $b.str('squirrels')]);
    var __pjs_iter0 = $b.foriter(_.a);
    while (__pjs_iter0.trynext()) {
        _.x = __pjs_iter0.value;
    
        $b.print(_.x);//, true
    }
    _.a = $b.dict([[$b.str('a'), 1], [$b.str('b'), 2], [$b.str('c'), 3]]);
    _.keys = $b.list([]);
    var __pjs_iter0 = $b.foriter(_.a);
    while (__pjs_iter0.trynext()) {
        _.x = __pjs_iter0.value;
    
        _.keys.append(_.x);
    }
    _.keys.sort();
    var __pjs_iter0 = $b.foriter(_.keys);
    while (__pjs_iter0.trynext()) {
        _.k = __pjs_iter0.value;
    
        $b.print(_.k);//, true
    }
    _.a = $b.str('defabc');
    var __pjs_iter0 = $b.foriter(_.a);
    while (__pjs_iter0.trynext()) {
        _.x = __pjs_iter0.value;
    
        $b.print(_.x);//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/basic/for_in.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

