/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/basic/generator.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/basic/generator.py', function (_) {
    _.__doc__ = "";
    _.generator = Class('generator', [], (function(){
        var __1 = {};
        __1.iterator = Class('iterator', [], (function(){
            var __2 = {};
            __2.__init__ = $def(function $___init__(self, parent) { // 5
                self.parent = parent;
                self.value = parent.min;
            });
            __2.__init__.__module__ = _.__name__;
            __2.__init__.__name__ = $b.str("__init__");
            __2.next = $def(function $_next(self) { // 9
                var val = self.value;
                if ($b.bool($b.do_ops(val, '>', self.parent.max)) === true) {
                    $b.raise($b.StopIteration);
                }
                self.value = $b.add(self.value, 1);
                return val;
            });
            __2.next.__module__ = _.__name__;
            __2.next.__name__ = $b.str("next");
            return __2;
        }()));
        __1.iterator.__module__ = _.__name__;
        __1.__init__ = $def(function $___init__(self, min, max) { // 16
            self.min = min;
            self.max = max;
        });
        __1.__init__.__module__ = _.__name__;
        __1.__init__.__name__ = $b.str("__init__");
        __1.__iter__ = $def(function $___iter__(self) { // 20
            return self.iterator(self);
        });
        __1.__iter__.__module__ = _.__name__;
        __1.__iter__.__name__ = $b.str("__iter__");
        return __1;
    }()));
    _.generator.__module__ = _.__name__;
    _.g = _.generator(5, 10);
    var __pjs_iter0 = $b.foriter(_.g);
    while (__pjs_iter0.trynext()) {
        _.v = __pjs_iter0.value;
    
        $b.print(_.v);//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/basic/generator.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

