/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/basic/kwargs.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/basic/kwargs.py', function (_) {
    _.__doc__ = "";
    _.myfunc = $def({}, true, true, function $_myfunc(a, b, c, d) { // 1
        $b.print(a);//, true
        $b.print(b);//, true
        var __pjs_iter0 = $b.foriter(c);
        while (__pjs_iter0.trynext()) {
            var i = __pjs_iter0.value;
        
            $b.print(i);//, true
        }
        var keys = d.keys();
        keys.sort();
        var __pjs_iter0 = $b.foriter(keys);
        while (__pjs_iter0.trynext()) {
            i = __pjs_iter0.value;
        
            $b.print(i);//, true
            $b.print(d.__getitem__(i));//, true
        }
    });
    _.myfunc.__module__ = _.__name__;
    _.myfunc.__name__ = $b.str("myfunc");
    _.myfunc.args($b.tuple([1, 2]), {'bar': $b.str('a'), 'foo': $b.str('c')});
    $b.print();//, true
    _.myfunc.args($b.tuple([1, 2, 3, 4]), {'bar': $b.str('a'), 'foo': $b.str('c')});
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/basic/kwargs.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

