/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/basic/oo_attributes.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/basic/oo_attributes.py', function (_) {
    _.__doc__ = "";
    _.Foobar = Class('Foobar', [$b.object], (function(){
        var __1 = {};
        __1.foo = 1;
        __1.bar = $b.list([1, 2, 3]);
        return __1;
    }()));
    _.Foobar.__module__ = _.__name__;
    _.my_foobar = _.Foobar();
    $b.print(_.my_foobar.foo);//, true
    $b.print(_.my_foobar.bar);//, true
    $b.print(_.Foobar.foo);//, true
    $b.print(_.Foobar.bar);//, true
    _._.my_foobar.foo = 2;
    _.my_foobar.bar.append(5);
    $b.print(_.my_foobar.foo);//, true
    $b.print(_.my_foobar.bar);//, true
    $b.print(_.Foobar.foo);//, true
    $b.print(_.Foobar.bar);//, true
    _._.Foobar.foo = 3;
    _.Foobar.bar.append(6);
    $b.print(_.my_foobar.foo);//, true
    $b.print(_.my_foobar.bar);//, true
    $b.print(_.Foobar.foo);//, true
    $b.print(_.Foobar.bar);//, true
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/basic/oo_attributes.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

