/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/basic/oo_static_inherit.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/basic/oo_static_inherit.py', function (_) {
    _.__doc__ = "";
    _.a1 = Class('a1', [$b.object], (function(){
        var __1 = {};
        __1.msg = $b.staticmethod($def(function $_msg(val) { // 5
            $b.print($b.add($b.str('a1 static method msg says:'), $b.str(val)));//, true
        }));
        __1.msg.__module__ = _.__name__;
        __1.msg.__name__ = $b.str("msg");
        return __1;
    }()));
    _.a1.__module__ = _.__name__;
    _.a2 = Class('a2', [_.a1], (function(){
        var __1 = {};
        
        return __1;
    }()));
    _.a2.__module__ = _.__name__;
    _.a = _.a2();
    _.a.msg($b.str('hello'));
    _.a2.msg($b.str('world'));
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/basic/oo_static_inherit.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

