/*** File generated by PJs http://jaredforsyth.com/projects/pjs ***/

// from source file /home/jared/clone/pjs/test/py2js/basic/trueorfalse.py

load("./build/pjslib.js");
var console = {log:function(){print.apply(this, arguments);}};
module('/home/jared/clone/pjs/test/py2js/basic/trueorfalse.py', function (_) {
    _.__doc__ = "";
    _.literals = $b.list([$b.str('a'), $b.str(''), 0, $b.None, 1, $b._float(0.000000), $b._float(1.000000), -1, $b._float(-1.000000), 0]);
    var __pjs_iter0 = $b.foriter(_.literals);
    while (__pjs_iter0.trynext()) {
        _.l = __pjs_iter0.value;
    
        if ($b.bool(_.l) === true) {
            $b.print($b.str('True'));//, true
        } else $b.print($b.str('False'));//, true
    }
});

__builtins__.__import__('sys').argv = __builtins__.list(arguments);
__builtins__.run_main('/home/jared/clone/pjs/test/py2js/basic/trueorfalse.py', ['/home/jared/clone/pjs', '/home/jared/clone/pjs', '/home/jared/python', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages']);

